development:
  adapter: postgresql
  database: streetlight_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: streetlight_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: streetlight_production
  pool: 5
  timeout: 5000